FROM maven:3.8-jdk-11 AS build
WORKDIR /yas/cart/
COPY ../pom.xml /yas/
COPY pom.xml /yas/cart/pom.xml
COPY src /yas/cart/src
COPY .mvn /yas/cart/.mvn
COPY mvnw /yas/cart/mvnw
RUN chmod +x /yas/cart/mvnw
RUN ls -la /yas
RUN ./mvnw clean packge -DskipTests


FROM eclipse-temurin:21-jre-alpine
COPY --from=build /yas/cart/target/cart*.jar /app.jar
ENTRYPOINT [ "java", "-jar", "/app.jar" ]
