pipeline{
    agent any
    stages{
        stage('Build'){
            steps{
               sh 'mvn clean package -pl backoffice -am'
               sh 'ls -l backoffice/target'  
            }
        }
    }
}